name: Build and Push Docker image
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 使用最新版的 checkout action
      
    - name: Free Disk Space (Ubuntu)    
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: false
        
    - name: Free disk space2
      run: |
             sudo apt clean
             sudo apt-get autoremove -y  
             sudo apt-get autoclean -y  
             docker rmi $(docker image ls -aq)
             df -h
        
#    - name: free disk space
      #run: |
        #sudo swapoff -a
        #sudo rm -f /swapfile   /opt/ghc
        #sudo apt clean
#        #docker rmi $(docker image ls -aq)
        #sudo apt-get autoremove -y  
        #sudo apt-get autoclean -y  
        #docker rmi $(docker image ls -aq)  
        #df -h
#    - name: Create Docker Volume
#      run: |
#        docker volume create --name myvolume --opt type=none --opt device=/mnt --opt o=bind      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx (可选，用于支持多平台构建)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKER_USERNAME }}/vllm:telechat  # 修改为您的 Docker Hub 用户名和期望的镜像标签
        load: false
#        cache-from: type=volume,src=myvolume
#        cache-to: type=volume,dest=myvolume
    #- name: Cleanup workspace
    #- run: rm -rf path/to/temp/files
    #- run: docker system prune -af  # 清理未使用的 Docker 对象
